---
title: "DS1_Lab4"
output: html_document
date: "2022-11-09"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(fields)
library(GGally)

```

# Problem 1
```{r}
library(datasets)
data(iris)
summary(iris)
```

```{r}
set.seed(100) 

k_means <- function(data, k, iter){
  # randomly assigning each observation to a cluster
  data <- data %>%
    mutate(cluster = sample(1:k, nrow(data), replace = TRUE))
  # calculate the centroids 
  centroids <- data %>%
    group_by(cluster) %>%
    summarise(across(everything(), mean)) %>%
    select(Sepal.Length:Petal.Width)
  # calculate distance
  points <- data %>%
    select(Sepal.Length:Petal.Width)
  for (i in iter){
    # select the minimum distance
    min_dis<- apply(rdist(centroids, points), 2, which.min)
  }
  return(min_dis) 
}

# Data Wrangling 
data(iris)

iris <- iris %>% select(-Species) 

# Scaling the Data
iris_scaled <- as.data.frame(scale(iris))

k_means(iris_scaled, 3, 50)
```


# Problem 2

```{r message = FALSE, warning=FALSE}
set.seed(2)

# Clustering
cluster <- k_means(iris_scaled, 3, 50)     

# Adding Cluster Value to the Table 
iris_scaled <- mutate(iris_scaled, 
                      cluster_val = cluster)  

iris_scaled$cluster_val <- as.factor(iris_scaled$cluster_val)  

# Plotting Characteristics
ggpairs(iris_scaled, 
        legend = 1, 
        columns = c("Sepal.Length", 
                    "Sepal.Width", 
                    "Petal.Length",
                    "Petal.Width"),
        columnLabels = c("Sepal Length", 
                         "Sepal Width", 
                         "Petal Length", 
                         "Petal Width"),
        aes(color = cluster_val), 
        title="Visualizing Sepal Characteristics by Clusters") + 
  labs(fill='Cluster') 


```


# Problem 3


